#                                                            #
#                    Nyex Gaming - Spigot                    #
#                          V 1.0.0                           #
#                                                            #
#      ⇝ Loja: https://nyexgaming.com.br/                    #
#      ⇝ Discord: https://comunidade.nyexgaming.com.br/      #
#                                                            #

credentials:
  access-store: 'CREDENCIAIS DA LOJA'
  access-server: 'CREDENCIAIS DO SERVIDOR'

database:
  #                                                     #
  #   Qual o banco de dados você deseja utilizar?       #
  #                                                     #
  #   MYSQL: jdbc:mysql://<host:port>/<database>        #
  #   SQLITE: jdbc:sqlite:<caminho>                     #
  #                                                     #
  jdbcUrl: 'jdbc:sqlite:plugins/NyexGaming/sqlite.db'

  #                                                     #
  #   Qual o usuário e senha do seu banco de dados?     #
  #   Se for sqlite, ignore essa configuração.          #
  #                                                     #
  user: 'root'
  password: 'password'

#                                                       #
#   Comandos que serão executados caso o jogador peça   #
#   reembolso em alguma compra ENTREGUE.                #
#                                                       #
chargeback-commands:
  - 'ban <jogador>'

modules:
  broadcast:
    #                                                     #
    #     Esse sistema encontra-se em desenvolvimento.    #
    #                                                     #
    status: false

  storage:
    #                                                     #
    #   Você deseja ativar o sistema de armazem?          #
    #   Deixe como false para ativar automaticamente.   #
    #                                                     #
    status: true

    #                                                     #
    #   Permitir que as compras sejam doados?             #
    #                                                     #
    donations: true

    #                                                     #
    #   Você deseja NPCs para abrir o armazém?            #
    #   Essa funcionalidade requer o plugin Citizens.     #
    #                                                     #
    npcs: true
