main: br.com.nyexgaming.mc.spigot.NyexPlugin

name: NyexPlugin
description: 'Plugin de integração da plataforma NyexGaming.'
version: 2.0.0

softdepend:
  - Citizens

author: WesleyGames001
website: nyexgaming.com.br

commands:
  nyexgaming:
    aliases:
      - nyexplugin
    description: 'Comando administrativo do plugin.'
    permission: nyexgaming.command.admin
  nyexstorage:
    aliases:
      - nyexarmazem
    description: 'Ative ou doe os produtos da loja.'
    permission: nyexgaming.command.storage
